server:
  port: 80

spring:
  cloud:
    gateway:
      routes:
      - id: user-api
        uri: http://ip-172-31-14-162.ap-northeast-2.compute.internal:8080
        predicates:
        - Path=/user/**
        filters:
        - RewritePath=/user/(?<path>.*), /$\{path}
      - id: order-api
        uri: http://ip-172-31-14-142.ap-northeast-2.compute.internal:8080
        predicates:
        - Path=/order/**
        filters:
        - RewritePath=/order/(?<path>.*), /$\{path}