server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://commerce-mysql.c90qy2aumeaj.ap-northeast-2.rds.amazonaws.com:3306/user
    username: commerce
    password: commerce

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true