server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/zeroorder?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: commerce
    password: commerce

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true