server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://commerce-mysql.c90qy2aumeaj.ap-northeast-2.rds.amazonaws.com:3306/orders
    username: commerce
    password: commerce

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  redis:
    host: commerceredis-ro.scxzeb.ng.0001.apn2.cache.amazonaws.com
    port: 6379